FROM twobombs/qracknet

RUN apt install pocl-opencl-icd docker.io

RUN distribution=$(. /etc/os-release;echo $ID$VERSION_ID) 
RUN curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey |  apt-key add - 
RUN curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list
RUN apt-get update && apt-get install -y nvidia-docker2 

EXPOSE 22 80 8801-8811
ENTRYPOINT /root/run-node
