FROM twobombs/qracknet

RUN tar -xf /qracknet/qrack-cosmos.tar.gz -C /var/log/
RUN apt install time
RUN cd /qracknet/scripts && /usr/bin/time ./maketipsy.sh

EXPOSE 22 80 8801-8811

ENTRYPOINT /root/run-node
