FROM twobombs/qracknet

RUN curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey |  apt-key add - 
RUN curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list
RUN apt-get update && apt-get install -y nvidia-docker2 pocl-opencl-icd docker.io && apt-get clean all

EXPOSE 22 80 8801-8811
ENTRYPOINT /root/run-node
