FROM twobombs/qracknet

RUN apt update
RUN apt install nvidia-cuda-toolkit 
RUN # apt install libopenmpi-dev && pip3 install mpi4py
RUN git clone https://github.com/treecode/Bonsai.git
RUN cd /Bonsai/runtime && cmake -DCMAKE_CXX_COMPILER=mpicxx -DUSE_CUB=0 -USE_OPENGL=1 && make 

EXPOSE 22 6080 8801-8811
ENTRYPOINT /root/run-node
