#!/bin/bash

# start monitoring of kubelet state & qrack output
metricbeat setup
service metricbeat start
service filebeat start

# auditbeat setup
# auditbeat -e
# service apm-server start

# start the SimulaQron, ProjectQ, Qrack train
simulaqron set backend projectq
simulaqron

# run benchmark for output simulation
cd /qrack/_build/
./benchmarks --single --layer-qfusion -m=-1 --proc-opencl-single test_qft_permutation_round_trip_entangled

# TODO: output logging storage

# end run, do not stop container ( debug feature )
tail -f /dev/null
