#!/bin/bash
# run node instance ( under development - not all services integrated )

# X-run script for non-nvidia hosts
rm /tmp/.X0-lock
export LIBGL_ALWAYS_SOFTWARE=1&&Xvfb :0 -screen 0 1280x720x24 -ac&
sleep 10
export DISPLAY=:0&&startxfce4&
sleep 10
x0vncserver -display :0 -passwordfile /root/.vnc/passwd&
libvirtd -d && service virtlogd start && service libvirt-bin start && brctl addbr br0 && service ssh start

# start web services
service nginx start && spawn-fcgi -s /var/run/fcgiwrap.socket /usr/sbin/fcgiwrap

# precompile cl kernels for Qrack
qrack_cl_precompile

# start the SimulaQron, ProjectQ, Qrack train
simulaqron set backend projectq
simulaqron

# run 5900 vncserver - nofork
/usr/share/novnc/utils/launch.sh --vnc localhost:5900 &

# run benchmark for output simulation
cd /qrack/_build/
./benchmarks --single --layer-qfusion -m=-1 --proc-opencl-single

# TODO: output logging storage

# end run
