#!/bin/bash

# start monitoring of kubelet state & qrack output
metricbeat setup &
service metricbeat start &
service filebeat start &

# start the SimulaQron, ProjectQ, Qrack train
simulaqron set backend projectq &
simulaqron &

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --single --proc-opencl-single --layer-qfusion -m=-1 --measure-output=/var/log/measured_supreme.csv [supreme]
./benchmarks --single --proc-opencl-single --layer-qfusion -m=-1 --measure-output=/var/log/measured_cosmos.csv [cosmos]
./benchmarks --single --proc-opencl-single --layer-qfusion -m=-1 --measure-output=/var/log/measured_qft.csv [qft]

# end run, do not stop container ( debug feature )
tail -f /dev/null
