#!/bin/bash

rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/

x0vncserver -display $DISPLAY -passwordfile /root/.vnc/passwd &
/usr/share/novnc/utils/launch.sh --vnc localhost:5900&

ulimit -s unlimited
nvidia-smi

cd /Bonsai/runtime && ./bonsai2_slowdust -i model3_child_compact.tipsy

# tail -f /dev/null
