#!/bin/bash

rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/

x0vncserver -display $DISPLAY -passwordfile /root/.vnc/passwd &
/usr/share/novnc/utils/launch.sh --vnc localhost:5900&

ulimit -s unlimited
nvidia-smi

startxfce4 &

cd /Bonsai/runtime/ && ./bonsai2_slowdust --displayfps -t 0.00001 --reducebodies 3 -i /thereminq/buildscripts/tipsy-qube_hexdump.bin &
cd /thereminq/buildscripts && ./makeqftipsy.sh && cd /Bonsai/runtime/ && ./bonsai2_slowdust --displayfps -t 0.00001 --reducebodies 3 -i /thereminq/buildscripts/tipsy-qube_hexdump.bin
