#!/bin/bash

rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/

x0vncserver -display $DISPLAY -passwordfile /root/.vnc/passwd &
/usr/share/novnc/utils/launch.sh --vnc localhost:5900&
service xrdp start && xrdp &

ulimit -s unlimited
nvidia-smi

startxfce4 &

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile &

export DISPLAY=:0&&xterm -e "xset s off" &
export DISPLAY=:0&&xterm -e "neofetch && tail -f /dev/null" &

tail -f /dev/null
