#!/bin/bash

# start the SimulaQron, ProjectQ, Qrack train
# simulaqron set backend projectq &
# simulaqron &

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --optimal --measure-shots=1024 -m=-1 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_$(date +%F_%R_%S).log" test_universal_circuit_analog

# end run, do not stop container ( debug feature )
# tail -f /dev/null
