#!/bin/bash
# WebUI@6080
rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/
export LIBGL_ALWAYS_SOFTWARE=0&&Xvfb :0 -screen 0 1920x1080x24+32 -ac &
service xrdp start &
sleep 10
export DISPLAY=:0&&startxfce4&	
x0vncserver -display :0 -passwordfile /root/.vnc/passwd&
/usr/share/novnc/utils/launch.sh --vnc localhost:5900&
xrdp &

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile &

export DISPLAY=:0&&xterm -e "xset s off" &
export DISPLAY=:0&&xterm -e "neofetch && tail -f /dev/null" &



# start rsaConverter, firefox session with lower yield rsa keygen site 
# and qimcifa on C ( which might eat the host ) 
#
export DISPLAY=:0 && gnome-calculator &
export DISPLAY=:0 && google-chrome-stable --disable-fre --no-default-browser-check --no-first-run --no-sandbox --password-store=basic https://www.mobilefish.com/services/rsa_key_generation/rsa_key_generation.php https://bigprimes.org/RSA-challenge  &
export DISPLAY=:0 && gnome-terminal &

export DISPLAY=:0&&xterm -e "xset s off"
export DISPLAY=:0&&xterm -e "neofetch && tail -f /dev/null" &

# end run, do not stop container ( debug feature, we need an empty node doing nothing )
tail -f /dev/null
