#!/bin/bash

# start rsaConverter, firefox session with lower yield rsa keygen site 
# and qimcifa on C ( which might eat the host ) 
#
export DISPLAY=:0 && gnome-calculator &
export DISPLAY=:0 && google-chrome-stable --disable-fre --no-default-browser-check --no-first-run --no-sandbox --password-store=basic https://www.mobilefish.com/services/rsa_key_generation/rsa_key_generation.php &
export DISPLAY=:0 && gnome-terminal &

export DISPLAY=:0&&xterm -e "xset s off"
export DISPLAY=:0&&xterm -e "neofetch && tail -f /dev/null" &

# end run, do not stop container ( debug feature, we need an empty node doing nothing )
tail -f /dev/null
