#!/bin/bash
cd /qrack128/_build

# export QRACK_QPAGER_DEVICES_HOST_POINTER=8.0,4.1,4.2
# export QRACK_QBDT_DEFAULT_OPT_IN=1
# export QRACK_ENABLE_QUNITMULTI_REDISTRIBUTE=1
# K80 only

export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.45
export QRACK_QPAGER_DEVICES=6.1,6.2
export QRACK_OCL_DEFAULT_DEVICE=1
export QRACK_MAX_PAGING_QB=31

time ./benchmarks --proc-stabilizer-qpager --layer-qunit-multi --max-qubits=33 --single --samples=10 test_qft_cosmology --measure-output=/var/log/qrack/"measured_qft_$(date +%F_%R_%S).log"
