#!/bin/bash

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --optimal --measure-shots=1024 --single --device-id=1 --samples=10000 --measure-output=/var/log/qrack/"measured_cosmos_$(date +%F_%R_%S).log" test_qft_cosmology &
sleep 5
./benchmarks --optimal --measure-shots=1024 --single --device-id=0 --samples=10000 --measure-output=/var/log/qrack/"measured_cosmos_$(date +%F_%R_%S).log" test_qft_cosmology

# end run, do not stop container ( debug feature )
# tail -f /dev/null
