#!/bin/bash

# start the SimulaQron, ProjectQ, Qrack train
# simulaqron set backend projectq &
# simulaqron &

# precompile cl kernels for Qrack	
cd /qrack128/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
# export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.146466 &&

./benchmarks --optimal --measure-shots=1024 -m=36 --benchmark-depth=36 --device-id=1 --samples=10 --measure-output=/var/log/qrack/"t_nn_d_$(date +%F_%R_%S).log" test_stabilizer_t_nn

# end run, do not stop container ( debug feature )
# tail -f /dev/null
