#!/bin/bash

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --optimal --measure-shots=1024 --single -m=12 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=14 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=16 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=18 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=20 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=22 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=24 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=26 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog

# end run, do not stop container ( debug feature )
# tail -f /dev/null
