#!/bin/bash
# WebUI@6080
rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/
export LIBGL_ALWAYS_SOFTWARE=1&&Xvfb :0 -screen 0 1920x1080x24+32 -ac&
sleep 10
export DISPLAY=:0&&startxfce4&	
x0vncserver -display :0 -passwordfile /root/.vnc/passwd&
/usr/share/novnc/utils/launch.sh --vnc localhost:5900&

export DISPLAY=:0 && xterm -e "xset s off"

# start monitoring of kubelet state & qrack output
filebeat setup -e
metricbeat setup &
service metricbeat start &
service filebeat start &

# start rsaConverter, firefox session with lower yield rsa keygen site 
# and qimcifa on C ( which might eat the host ) 
#
export DISPLAY=:0 && gnome-calculator &
export DISPLAY=:0 && google-chrome-stable --no-sandbox --password-store=basic https://www.mobilefish.com/services/rsa_key_generation/rsa_key_generation.php &
export DISPLAY=:0 && gnome-terminal

# end run, do not stop container ( debug feature, we need an empty node doing nothing )
tail -f /dev/null
