#!/bin/bash
# cd /qrack/_build
# 

# QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.10
export QRACK_OCL_DEFAULT_DEVICE=0
export QRACK_QPAGER_DEVICES=9.0,9.4,9.2,9.4,9.1,9.4,9,0,9.4
export QRACK_QPAGER_DEVICES_HOST_POINTER=9.0,0.1
export QRACK_MAX_ALLOC_MB=72000
export QRACK_MAX_PAGING_QB=32
export QRACK_MAX_CPU_QB=32
export QRACK_SEGMENT_GLOBAL_QB=4

time ./benchmarks --optimal --single --max-qubits=32 --samples=1 test_qft_cosmology  --measure-output=/var/log/qrack/"measured_qft_$(date +%F_%R_%S).log"
