#!/bin/bash

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

#export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.40
#export QRACK_QPAGER_DEVICES=12.2
#export QRACK_QPAGER_DEVICES_HOST_POINTER=12.0,1.1
export QRACK_OCL_DEFAULT_DEVICE=0
#export QRACK_MAX_ALLOC_MB=12000

#export QRACK_MAX_PAGING_QB=26
export QRACK_MAX_PAGE_QB=25

#export QRACK_SEGMENT_GLOBAL_QB=2

# run benchmark for load & output simulation

for run in {1..100}; do

echo $run

./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=8 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_8_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=9 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_9_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=10 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_10_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=11 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_11_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=12 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_12_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=13 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_13_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=14 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_14_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=15 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_15_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=16 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_16_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=17 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_17_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=18 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_18_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=19 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_19_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=20 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_20_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=21 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_21_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=22 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_22_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=23 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_23_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=24 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_24_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=25 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_25_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=26 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_26_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=0,0,0,0 --use-host-dma --measure-shots=10000 --single -m=27 --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_27_$run-$(date +%F_%R_%S).log" test_qft_cosmology

done

# sleep 5
# ./benchmarks --optimal --measure-shots=1024 --proc-stabilizer-qpager -m=27 --device-id=1 --single --samples=1000 --measure-output=/var/log/qrack/"measured_cosmos_$(date +%F_%R_%S).log" test_qft_cosmology

# end run, do not stop container ( debug feature )
# tail -f /dev/null
