#!/bin/bash
#
# run TNN benchmark for load & output simulation 

export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.50
export QRACK_QPAGER_DEVICES=10.1
#,10.0
#,11.1,11.4
export QRACK_QPAGER_DEVICES_HOST_POINTER=10.0,4.1
export QRACK_OCL_DEFAULT_DEVICE=1
export QRACK_MAX_PAGING_QB=32
export QRACK_MAX_ALLOC_MB=10000
#
time ./benchmarks --optimal-single --timeout=2000 --max-qubits=27 --benchmark-depth=420 --single test_stabilizer_t_cc_nn --samples=10 --measure-output=/var/log/qrack/"t_cc_nn_$(date +%F_%R_%S).log"
