#!/bin/bash
#
export CUDA_VISIBLE_DEVICES=2,1
#
cd /qrack128/_build

# export QRACK_QPAGER_DEVICES_HOST_POINTER=8.0,4.1,4.2
# export QRACK_QBDT_DEFAULT_OPT_IN=1
# export QRACK_ENABLE_QUNITMULTI_REDISTRIBUTE=1
# K80 only

export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.45
export QRACK_QPAGER_DEVICES=6.0,6.1
export QRACK_OCL_DEFAULT_DEVICE=0
export QRACK_MAX_PAGING_QB=31

time ./benchmarks --proc-stabilizer-qpager --layer-qunit-multi --timeout=2000000 --max-qubits=52 --benchmark-depth=20 --single test_quantum_supremacy --samples=100 --measure-output=/var/log/qrack/"supreme_$(date +%F_%R_%S).log"

