#!/bin/bash
# WebUI@6080
rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/
# export LIBGL_ALWAYS_SOFTWARE=1&&Xvfb :0 -screen 0 1280x720x24 -ac&	
# export DISPLAY=:0&&startxfce4&	
# x0vncserver -display :0 -passwordfile /root/.vnc/passwd&

# start monitoring of kubelet state & qrack output
filebeat setup -e
metricbeat setup &
service metricbeat start &
service filebeat start &

# precompile cl kernels for Qrack	
cd /qrack128/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.146466 && export QRACK_OCL_DEFAULT_DEVICE=0 && ./benchmarks --use-host-dma --optimal --max-qubits=64 --benchmark-depth=8 --devices=0,0,0,0,1,1,1,1 --single test_stabilizer_t_nn_d --samples=1000 --measure-output=/var/log/qrack/"t_nn_d_$(date +%F_%R_%S).log" test_stabilizer_t_nn_d
sleep 5
export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.146466 && export QRACK_OCL_DEFAULT_DEVICE=1 && ./benchmarks --use-host-dma --optimal --max-qubits=64 --benchmark-depth=8 --devices=1,1,1,1,0,0,0,0 --single test_stabilizer_t_nn_d --samples=1000 --measure-output=/var/log/qrack/"t_nn_d_$(date +%F_%R_%S).log" test_stabilizer_t_nn_d

# end run, do not stop container ( debug feature )
# tail -f /dev/null
