#!/bin/bash

# precompile cl kernels for Qrack	
cd /qrack128/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
# export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.146466 && export QRACK_OCL_DEFAULT_DEVICE=0 && 
./benchmarks --use-host-dma --optimal --measure-shots=1024 --max-qubits=36 --benchmark-depth=36 --devices=0,0,0,0,1,1,1,1 --single test_stabilizer_t_nn --samples=1000 --measure-output=/var/log/qrack/"t_nn_d_$(date +%F_%R_%S).log" test_stabilizer_t_nn_d &&
sleep 5
# export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.146466 && export QRACK_OCL_DEFAULT_DEVICE=1 && 
./benchmarks --use-host-dma --optimal --measure-shots=1024 --max-qubits=36 --benchmark-depth=36 --devices=1,1,1,1,0,0,0,0 --single test_stabilizer_t_nn --samples=1000 --measure-output=/var/log/qrack/"t_nn_d_$(date +%F_%R_%S).log" test_stabilizer_t_nn_d

# end run, do not stop container ( debug feature )
# tail -f /dev/null
