#!/bin/bash

rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/

x0vncserver -display $DISPLAY -passwordfile /root/.vnc/passwd &
/usr/share/novnc/utils/launch.sh --vnc localhost:5900&

ulimit -s unlimited
nvidia-smi

startxfce4 &

cd /Bonsai/runtime && ./bonsai2_slowdust -t 0.00001 --displayfps -T 1000 -i /thereminq/buildscripts/sycamore_sphere/qrack-supreme12-28q14d10k/sycamore_spheres_tipsy_bowl_hexdump.bin

tail -f /dev/null
