#!/bin/bash

#!/bin/bash
# WebUI@6080
rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/
export LIBGL_ALWAYS_SOFTWARE=0&&Xvfb :0 -screen 0 1920x1080x24+32 -ac &
service xrdp start &
sleep 10
export DISPLAY=:0&&startxfce4&	
x0vncserver -display :0 -passwordfile /root/.vnc/passwd&
/usr/share/novnc/utils/launch.sh --vnc localhost:5900&
xrdp &

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile &

export DISPLAY=:0&&xterm -e "xset s off" &
export DISPLAY=:0&&xterm -e "neofetch && tail -f /dev/null" &

# start vcl controller with nodes file from mount
cp /var/log/vcl/etc/vcl/nodes /etc/vcl/nodes

# start vcl backend and controller
cd /vcl-1.25/ && ./vcl start

tail -f /dev/null
