#!/bin/bash
#
# run TNN benchmark for load & output simulation 
# optional pointers:
# export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.146466 
# --use-host-dma
#
# QRACK_QPAGER_DEVICES is now set to the card with the highest memory first (24GB), then the second GPU ( that has 2 GPUs of 12Gb each )
# qrack128 compilation is optimised for high qubit operations. if you want to do <33Qbits use /qrack/_build
# https://github.com/twobombs/thereminq/blob/master/Dockerfiles/Dockerfile#L33
#
# for TNN the combination of stabilizer, qpager on qunit-multi currently has the best speed and optimisation
#
cd /qrack128/_build/
#
export QRACK_QPAGER_DEVICES=0,0,0,0,0,0,0,0,2,2,2,2,1,1,1,1
export QRACK_OCL_DEFAULT_DEVICE=0 && time ./benchmarks --proc-stabilizer-qpager --layer-qunit-multi --timeout=2000000 --max-qubits=49 --devices=0,0,0,0,0,0,0,0,2,2,2,2,1,1,1,1 --benchmark-depth=49 --single test_stabilizer_t_nn --samples=100 --measure-output=/var/log/qrack/"t_cc_$(date +%F_%R_%S).log" &
#
