#!/bin/bash
#
# run TNN benchmark for load & output simulation 
# optional pointers:
# export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.146466 
# --use-host-dma
#
# QRACK_QPAGER_DEVICES is now set to the card with the highest memory first (24GB), then the second GPU ( that has 2 GPUs of 12Gb each )
# qrack128 compilation is optimised for high qubit operations. if you want to do <33Qbits use /qrack/_build
# https://github.com/twobombs/thereminq/blob/master/Dockerfiles/Dockerfile#L33
#
# for TNN the combination of stabilizer, qpager on qunit-multi currently has the best speed and optimisation
#
cd /qrack128/_build/
#
export QRACK_QPAGER_DEVICES=8.0,4.1,4.2
export QRACK_OCL_DEFAULT_DEVICE=0
export QRACK_MAX_PAGING_QB=32 
time ./benchmarks --proc-stabilizer-qpager --layer-qunit-multi --timeout=2000000 --max-qubits=44 --benchmark-depth=44 --single test_dense_cc_nn --samples=100 --measure-output=/var/log/qrack/"t_cc_dense_$(date +%F_%R_%S).log" &
#
