#!/bin/bash

# start the SimulaQron, ProjectQ, Qrack train
# simulaqron set backend projectq &
# simulaqron &

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation

./benchmarks --optimal --measure-shots=1024 --device-id=0 -m=27 --samples=10 --measure-output=/var/log/qrack/"measured_cosmos_$(date +%F_%R_%S).log" test_qft_cosmology

# end run, do not stop container ( debug feature )
# tail -f /dev/null
