#!/bin/bash

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --optimal --measure-shots=1024 --single -m=28 --benchmark-depth=14 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_universal_circuit_analog

# end run, do not stop container ( debug feature )
# tail -f /dev/null
