#!/bin/bash
#
# run TNN benchmark for load & output simulation 
# optional pointers:
# export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.146466 
# --use-host-dma
#
# QRACK_QPAGER_DEVICES is now set to the card with the highest memory first (24GB), then the second GPU ( that has 2 GPUs of 12Gb each )
# qrack128 compilation is optimised for high qubit operations. if you want to do <33Qbits use /qrack/_build
# https://github.com/twobombs/thereminq/blob/master/Dockerfiles/Dockerfile#L33
#
# for TNN the combination of stabilizer, qpager on qunit-multi currently has the best speed and optimisation
#
# cd /qrack128/_build/

export QRACK_MAX_PAGING_QB=40
export QRACK_MAX_CPU_QUBITS=40
export QRACK_MAX_ALLOC_MB=22000000
export QRACK_SEGMENT_GLOBAL_QB=0
#
time ./benchmarks --optimal-cpu --timeout=2000 --max-qubits=40 --benchmark-depth=400 --single test_stabilizer_t_cc_nn --samples=1 --measure-output=/var/log/qrack/"t_cc_nn_$(date +%F_%R_%S).log"
#

