#!/bin/bash

# start the SimulaQron, ProjectQ, Qrack train
# simulaqron set backend projectq &
# simulaqron &

# precompile cl kernels for Qrack	
# cd /qrack/_build/ && ./qrack_cl_precompile

#export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.40
#export QRACK_QPAGER_DEVICES=12.2
#export QRACK_QPAGER_DEVICES_HOST_POINTER=12.0,1.1
export QRACK_OCL_DEFAULT_DEVICE=2
#export QRACK_MAX_ALLOC_MB=12000

#export QRACK_MAX_PAGING_QB=26
export QRACK_MAX_PAGE_QB=26

#export QRACK_SEGMENT_GLOBAL_QB=2

# run benchmark for load & output simulation

for run in {1..100}; do

./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=1,1,1,1,1,1 --use-host-dma --measure-shots=10000 -m=28 --single --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_28_$run-$(date +%F_%R_%S).log" test_qft_cosmology
./benchmarks --optimal-single --layer-qtensornetwork --proc-bdt-hybrid --devices=1,1,1,1,1,1 --use-host-dma --measure-shots=10000 -m=29 --single --benchmark-depth=33 --samples=1 --measure-output=/var/log/qrack/"measured_cosmos_graph_29_$run-$(date +%F_%R_%S).log" test_qft_cosmology

done

# sleep 5
# ./benchmarks --optimal --measure-shots=1024 --proc-stabilizer-qpager -m=27 --device-id=1 --single --samples=1000 --measure-output=/var/log/qrack/"measured_cosmos_$(date +%F_%R_%S).log" test_qft_cosmology

# end run, do not stop container ( debug feature )
# tail -f /dev/null
