#!/bin/bash

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --optimal --measure-shots=1024 --single -m=12 --samples=1000 --benchmark-depth=14 --device-id=1 --measure-output=/var/log/qrack/"measured_supreme_gpu2$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=14 --samples=1000 --benchmark-depth=14 --device-id=1 --measure-output=/var/log/qrack/"measured_supreme_gpu2$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=16 --samples=1000 --benchmark-depth=14 --device-id=1 --measure-output=/var/log/qrack/"measured_supreme_gpu2$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=18 --samples=1000 --benchmark-depth=14 --device-id=1 --measure-output=/var/log/qrack/"measured_supreme_gpu2$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=20 --samples=1000 --benchmark-depth=14 --device-id=1 --measure-output=/var/log/qrack/"measured_supreme_gpu2$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=22 --samples=1000 --benchmark-depth=14 --device-id=1 --measure-output=/var/log/qrack/"measured_supreme_gpu2$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=24 --samples=1000 --benchmark-depth=14 --device-id=1 --measure-output=/var/log/qrack/"measured_supreme_gpu2$(date +%F_%R_%S).log" test_universal_circuit_analog
./benchmarks --optimal --measure-shots=1024 --single -m=26 --samples=1000 --benchmark-depth=14 --device-id=1 --measure-output=/var/log/qrack/"measured_supreme_gpu2$(date +%F_%R_%S).log" test_universal_circuit_analog

# end run, do not stop container ( debug feature )
# tail -f /dev/null
