#!/bin/bash
# WebUI@6080
rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/
# export LIBGL_ALWAYS_SOFTWARE=1&&Xvfb :0 -screen 0 1280x720x24 -ac&	
# export DISPLAY=:0&&startxfce4&	
# x0vncserver -display :0 -passwordfile /root/.vnc/passwd&

# start monitoring of kubelet state & qrack output
filebeat setup -e
metricbeat setup &
service metricbeat start &
service filebeat start &

# start the SimulaQron, ProjectQ, Qrack train
# simulaqron set backend projectq &
# simulaqron &

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation

./benchmarks --layer-qunit-multi-qpager --proc-hybrid -m=27 --devices 0,0,0,0,1,1,1,1 --device-id=0 --single --benchmark-samples=1000 --measure-output=/var/log/qrack/"measured_cosmos_$(date +%F_%R_%S).log" test_qft_cosmology &
sleep 5
./benchmarks --layer-qunit-multi-qpager --proc-hybrid -m=27 --devices 0,0,0,0,1,1,1,1 --device-id=1 --single --benchmark-samples=1000 --measure-output=/var/log/qrack/"measured_cosmos_$(date +%F_%R_%S).log" test_qft_cosmology

# end run, do not stop container ( debug feature )
# tail -f /dev/null
