#!/bin/bash
# WebUI@6080
rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/
# export LIBGL_ALWAYS_SOFTWARE=1&&Xvfb :0 -screen 0 1280x720x24 -ac&	
# export DISPLAY=:0&&startxfce4&	
# x0vncserver -display :0 -passwordfile /root/.vnc/passwd&

# start monitoring of kubelet state & qrack output
filebeat setup -e
metricbeat setup &
service metricbeat start &
service filebeat start &

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --proc-stabilizer-qpager --single -m=12 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_quantum_supremacy
./benchmarks --proc-stabilizer-qpager --single -m=14 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_quantum_supremacy
./benchmarks --proc-stabilizer-qpager --single -m=16 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_quantum_supremacy
./benchmarks --proc-stabilizer-qpager --single -m=18 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_quantum_supremacy
./benchmarks --proc-stabilizer-qpager --single -m=20 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_quantum_supremacy
./benchmarks --proc-stabilizer-qpager --single -m=22 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_quantum_supremacy
./benchmarks --proc-stabilizer-qpager --single -m=24 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_quantum_supremacy
./benchmarks --proc-stabilizer-qpager --single -m=26 --benchmark-depth=14 --samples=1000 --device-id=0 --measure-output=/var/log/qrack/"measured_supreme_gpu1$(date +%F_%R_%S).log" test_quantum_supremacy

# end run, do not stop container ( debug feature )
# tail -f /dev/null
