#!/bin/bash
# general 31 qubit vcl check
# assuming a minimal of 33 devices are created and avaliable
# QRACK_SEGMENT_GLOBAL_QB=5  = 32 devices
# run this inside the (qrackmin:)vcl host node
#
export QRACK_QPAGER_DEVICES=1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,1.10,1.11,1.12,1.13,1.14,1.15,1.16,1.17,1.18,1.19,1.20,1.21,1.22,1.23,1.24,1.25,1.26,1.27,1.28,1.29,1.30,1.31,1.32
export QRACK_QPAGER_DEVICES_HOST_POINTER=1.0,1.1
export QRACK_MAX_ALLOC_MB=4096
export QRACK_MAX_PAGING_QB=31
export QRACK_MAX_CPU_QB=31
export QRACK_SEGMENT_GLOBAL_QB=5

cd /vcl-1.25 && ./vclrun /qrack/_build/benchmarks --optimal --single --max-qubits=31 --samples=1 test_qft_cosmology  --measure-output=/var/log/qrack/"measured_vcl_qft_$(date +%F_%R_%S).log"
