#!/bin/bash
#
# run TNN benchmark for load & output simulation 
#
# export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.50
# export QRACK_QPAGER_DEVICES=10.1,10.0
# export QRACK_QPAGER_DEVICES_HOST_POINTER=10.0,4.1
export QRACK_OCL_DEFAULT_DEVICE=1
export QRACK_MAX_PAGING_QB=30
# export QRACK_MAX_ALLOC_MB=10000
export QRACK_MAX_PAGE_QB=27
#
# time ./benchmarks --optimal --measure-shots=1024 --timeout=2000 --max-qubits=30 --benchmark-depth=20 --single test_stabilizer_rz --samples=1 --measure-output=/var/log/qrack/"stab_rz_$(date +%F_%R_%S).log"
time ./benchmarks --optimal --measure-shots=1024 --benchmark-max-magic=3 --timeout=2000 --max-qubits=30 --benchmark-depth=20 --single test_stabilizer_rz --samples=1 --measure-output=/var/log/qrack/"stab_rz_$(date +%F_%R_%S).log"
