#!/bin/bash

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --optimal --measure-shots=1024 --device-id=0 --measure-output=/var/log/qrack/"measured_qft_gpu2$(date +%F_%R_%S).log" test_qft_permutation_round_trip_entangled &
sleep 5
./benchmarks --optimal --measure-shots=1024 --device-id=1 --measure-output=/var/log/qrack/"measured_qft_gpu2$(date +%F_%R_%S).log" test_qft_permutation_round_trip_entangled


# end run, do not stop container ( debug feature )
# tail -f /dev/null
