#!/bin/bash

# precompile cl kernels for Qrack	
cd /qrack/_build/ && ./qrack_cl_precompile

# run benchmark for load & output simulation
./benchmarks --optimal --measure-shots=1024 -m=-1 --device-id=0 --measure-output=/var/log/qrack/"t_nn_$(date +%F_%R_%S).log" test_stabilizer_t_nn

# end run, do not stop container ( debug feature )
# tail -f /dev/null
