FROM twobombs/thereminq:latest

RUN apt update && apt install gnome-calculator mathomatic-primes mathomatic
RUN git clone https://github.com/openssh/openssh-portable.git && cd openssh-portable && autoreconf && ./configure SSH_RSA_MINIMUM_MODULUS_SIZE=32 && make && make tests

EXPOSE 22 80 8801-8811
ENTRYPOINT /root/run-node
