FROM nvidia/cudagl:11.4.2-devel-ubuntu20.04

# install bonsai
RUN apt update && export DEBIAN_FRONTEND=noninteractive && apt install -y git cmake-curses-gui nvidia-cuda-toolkit && apt clean all
RUN git clone https://github.com/twobombs/Bonsai.git
RUN cd /Bonsai/runtime/lib && mv linux linux_temp && mv linux_fpic_glew linux
RUN cd /Bonsai/runtime && cmake -DCMAKE_CXX_COMPILER=mpicxx -DUSE_CUB=0 -DUSE_OPENGL=1 -DCUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so && make && cd /Bonsai/tools/IO && make

# add and convert demo data
# RUN tar -xf /thereminq/miscfiles/qrack-cosmos.tar.gz -C /var/log/
# RUN apt install time
# RUN cat /proc/cpuinfo > /thereminq/cpuinfo.txt

EXPOSE 22 6080 8801-8811
ENTRYPOINT /root/run-bonsai
