FROM twobombs/thereminq

RUN tar -xf /qracknet/miscfiles/qrack-cosmos.tar.gz -C /var/log/
RUN apt install time
RUN cat /proc/cpuinfo > /qracknet/cpuinfo.txt
RUN cd /qracknet/buildscripts && /usr/bin/time ./maketipsy.sh

EXPOSE 22 80 8801-8811

ENTRYPOINT /root/run-node
