FROM twobombs/qrackmin:1804

# install apt packages because 
RUN apt update && apt install -y cmake nodejs libssl-dev xxd libgmp3-dev pocl-opencl-icd && apt clean all

# install rsa primes UI & Shors' input requirement.
RUN add-apt-repository -y ppa:linuxuprising/libpng12 && apt update && apt install -y cmake xxd nodejs gnome-calculator mathomatic-primes mathomatic libssl-dev libgmp3-dev libgtest-dev gnome-calculator mathomatic-primes mathomatic libssl-dev libboost-all-dev opencl-headers xxd libpng12-0 libcanberra-gtk-module gtk2-engines-pixbuf libcanberra-gtk3-module && apt clean all
# npm

# nerfed rsa prime generators install
RUN git clone https://github.com/openssh/openssh-portable.git && cd openssh-portable && autoreconf && sed -i 's/#define SSH_RSA_MINIMUM_MODULUS_SIZE.*/#define SSH_RSA_MINIMUM_MODULUS_SIZE   1024/g' sshkey.h && ./configure && make && mkdir /var/empty && make tests && make install
RUN git clone https://github.com/openssl/openssl.git && cd openssl && ./Configure enable-weak-ssl-ciphers -DOPENSSL_TLS_SECURITY_LEVEL=0 && make && make install

# vm6502q/qimcifa has an LGPL license. Report (re)use of code to Dan Strano.
# RUN git clone --branch opencl_bigint https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa-bigint cd qimcifa-bigint && cmake . && make
RUN git clone https://github.com/vm6502q/qimcifa.git && cd /qimcifa && cmake . && make

# NV's BigINT implementation + reqs
# RUN git clone https://github.com/google/googletest.git && cd googletest && cmake . && make && make install 
# RUN git clone https://github.com/NVlabs/CGBN.git && cd CGBN && mv /googletest/googletest gtest && make kepler

RUN mkdir /var/log/shors && mkdir /var/log/qimcifa

EXPOSE 22 80 8801-8811
ENTRYPOINT /root/run-shors
