FROM twobombs/cudacluster:dev

# install CPU prime generator
RUN apt update && apt install -y gnome-calculator mathomatic-primes mathomatic libssl-dev cmake && apt clean all

# install CUDAsieve prime generator
RUN apt update && apt install -y libboost-all-dev libprimesieve-dev && apt clean all
RUN git clone https://github.com/curtisseizert/CUDASieve.git
RUN ln /usr/local/cuda /opt/cuda
RUN cd CUDASieve && mkdir obj && make && make test && make samples

# fetch & install mtsieve
RUN apt update && apt install -y subversion opencl-headers libgmp3-dev && ldconfig && ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so
RUN svn checkout https://svn.code.sf.net/p/mtsieve/svn/ mtsieve-svn
# build disabled because one of the sieves are borked
# RUN cd mtsieve-svn && make

# vm6502q/qimcifa has an LGPL license. Report (re)use of code to Dan Strano.
RUN git clone --branch opencl_bigint https://github.com/vm6502q/qimcifa.git && mv /qimcifa /qimcifa-bigint && cd /qimcifa-bigint && cmake . && make
RUN git clone https://github.com/vm6502q/qimcifa.git && cd /qimcifa && cmake . && make

# install haskell, z3, num-utils, crackNum + dependancies
RUN git clone https://github.com/LeventErkok/crackNum.git
RUN apt-get install -y z3 num-utils && apt clean all
RUN curl -sSL https://get.haskellstack.org/ | sh
RUN cd crackNum && stack path --local-bin && stack setup && stack init && stack build && stack install && stack clean && rm -R /crackNum

# install metricbeat for ES 7.4+ for pump-n-dump
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add - 
RUN apt-get install apt-transport-https
RUN echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-7.x.list
RUN apt-get update && apt-get install metricbeat filebeat auditbeat && filebeat modules enable elasticsearch && filebeat modules enable system && filebeat modules enable osquery
COPY configfiles/metricbeat.yml /etc/metricbeat/metricbeat.yml
COPY configfiles/filebeat.yml /etc/filebeat/filebeat.yml

RUN mkdir /var/log/sieve

EXPOSE 22 80 8801-8811
ENTRYPOINT /root/run-sieve
