FROM twobombs/thereminq:pocl

# install pocl 3 and pocl 4 and pre-5 build requirements
RUN apt update && add-apt-repository -y ppa:ocl-icd/ppa && apt install -y clang llvm clinfo ocl-icd-opencl-dev pocl-opencl-icd libopencl-clang-dev libclang-dev libclang-cpp-dev pkg-config libhwloc-dev python3-dev ocl-icd-libopencl1 ocl-icd-opencl-dev llvm-spirv-15 cmake && apt clean all
RUN apt install -y python3-dev libpython3-dev build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-dev clang llvm make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils libxml2-dev libclang-cpp-dev llvm-dev && apt clean all

# pre-pocl 5
RUN git clone https://github.com/pocl/pocl.git && cd pocl && mkdir build && cd build && cmake -G Ninja -DWITH_LLVM_CONFIG=/usr/bin/llvm-config-14 -DCMAKE_INSTALL_PREFIX=/usr .. && ninja install
RUN clinfo

# RUN ./qrack/_build/unittest --optimal-cpu --layer-qtensornetwork >/dev/null 2>&1

RUN ./qrack128/_build/unittest --optimal-cpu

EXPOSE 22 80 8801-8811
ENTRYPOINT /qrack/_build/unittest
