FROM microsoft/windowsservercore:latest

RUN powershell Install-PackageProvider NuGet -forcebootstrap -force
RUN powershell Register-PackageSource -name chocolatey -provider nuget -location http://chocolatey.org/api/v2/ -trusted

RUN powershell Install-Package openssh -provider NuGet
RUN powershell Install-Package sysinternals -provider NuGet
RUN powershell Install-Package VcXsrv -provider NuGet

RUN powershell Install-Package mc -provider NuGet
RUN powershell Install-Package vim -provider NuGet
RUN powershell Install-Package cmake -provider NuGet
RUN powershell Install-Package git -provider NuGet

RUN powershell git clone https://github.com/vm6502q/qrack.git
RUN cd qrack && mkdir _build && cd _build && cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DXXD_BIN="C:/Program Files (x86)/Vim/vim82/xxd.exe" -DFPPOW=6 ..

EXPOSE 22
