FROM twobombs/qrackmin

# install apt packages because 
RUN apt update && apt install -y cmake nodejs libssl-dev xxd libgmp3-dev pocl-opencl-icd && apt clean all

# install baseline x, vnc to support display qimcifa in remote X
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y apt-utils net-tools software-properties-common && dpkg --add-architecture i386 && apt-get update -y && apt-get install -y git wget curl net-tools qemu-kvm qemu nvidia-modprobe qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager linux-tools-generic && apt-get clean all && apt -y autoremove
RUN export DEBIAN_FRONTEND=noninteractive && apt-get install -y  --install-recommends xrdp xfce4 xfce4-goodies libsdl1.2-dev mesa-utils libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev && apt-get clean all && apt -y autoremove
RUN export DEBIAN_FRONTEND=noninteractive && apt-get install -y x11vnc neofetch tightvncserver tigervnc-scraping-server novnc xvfb xterm mc lynx open-vm-tools ssh-askpass-gnome && apt-get clean all && apt -y autoremove
RUN cp /usr/share/novnc/vnc.html /usr/share/novnc/index.html && mkdir /root/.vnc

# install rsa primes UI & Shors' input requirement.
# RUN add-apt-repository -y ppa:linuxuprising/libpng12
RUN apt update && apt install -y cmake xxd nodejs gnome-calculator mathomatic-primes mathomatic libssl-dev libgmp3-dev libgtest-dev gnome-calculator mathomatic-primes mathomatic libssl-dev libboost-all-dev opencl-headers xxd libcanberra-gtk-module gtk2-engines-pixbuf libcanberra-gtk3-module && apt clean all
# npm libpng12-0

# nerfed rsa prime generators install ( no need when RSA keys > 64 bits )
# RUN git clone --depth=1 https://github.com/openssh/openssh-portable.git && cd openssh-portable && autoreconf && sed -i 's/#define SSH_RSA_MINIMUM_MODULUS_SIZE.*/#define SSH_RSA_MINIMUM_MODULUS_SIZE   1024/g' sshkey.h && ./configure && make && mkdir /var/empty && make tests && make install
# RUN git clone --depth=1 https://github.com/openssl/openssl.git && cd openssl && ./Configure enable-weak-ssl-ciphers -DOPENSSL_TLS_SECURITY_LEVEL=0 && make && make install

# vm6502q/qimcifa has an LGPL license. Report (re)use of code to Dan Strano
# RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa64 && cd /qimcifa64 && cmake -DBIG_INT_BITS=64 . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa128 && cd /qimcifa128 && cmake -DBIG_INT_BITS=128 . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa512 && cd /qimcifa512 && cmake -DBIG_INT_BITS=512 . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa1024 && cd /qimcifa1024 && cmake -DBIG_INT_BITS=512 . && make
# old bigint build
RUN git clone --depth=1 --branch opencl_bigint https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa-bigint && cd qimcifa-bigint && cmake . && make

# NV's BigINT implementation + reqs
# RUN git clone --depth=1 https://github.com/google/googletest.git && cd googletest && cmake . && make && make install 
# RUN git clone --depth=1 https://github.com/NVlabs/CGBN.git && cd CGBN && mv /googletest/googletest gtest && make kepler

RUN mkdir /var/log/shors && mkdir /var/log/qimcifa

# git clone thereminq-tensors scripts 
RUN git clone --depth=1 https://github.com/twobombs/thereminq-tensors.git

# vnc settings
COPY configfiles/xorg.conf /usr/share/X11/xorg.conf.d/
COPY configfiles/passwd /root/.vnc/
COPY configfiles/xstartup /root/.vnc/
RUN chmod 755 /root/.vnc/xstartup

EXPOSE 22 80 8801-8811
ENTRYPOINT /root/run-shors
